# Generated by Django 5.1.7 on 2025-03-15 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fill_created_by(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    for order in Order.objects.all():
        order.created_by = order.member
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_group_grouporder_group_order_group_groupmember_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="on_behalf_orders",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(fill_created_by, migrations.RunPython.noop),
    ]
