# Generated by Django 4.2.13 on 2024-06-01 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_grouporder_actual_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouporder",
            name="actual_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                editable=False,
                max_digits=11,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
