# Generated by Django 4.2.13 on 2024-05-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
